-- Create roles table if not exists
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

-- Create users table if not exists
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL
);

-- Create user_roles junction table if not exists
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Create blogs table if not exists
CREATE TABLE IF NOT EXISTS blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author VARCHAR(50) NOT NULL,
    publish_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX idx_user_username ON users(username);
CREATE INDEX idx_blog_author ON blogs(author);
CREATE INDEX idx_blog_date ON blogs(publish_date);

-- Create articles table if not exists
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    content TEXT NOT NULL,
    read_time VARCHAR(50),
    category VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    publish_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create article_tags table if not exists
CREATE TABLE IF NOT EXISTS article_tags (
    article_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    PRIMARY KEY (article_id, tag),
    FOREIGN KEY (article_id) REFERENCES articles(id)
);

-- Create indexes for articles
CREATE INDEX idx_article_category ON articles(category);
CREATE INDEX IF NOT EXISTS idx_article_publish_date ON articles(publish_date);

-- Ebooks content table: Global catalog & site config (single row)
-- Purpose:
--   - Aggregated author/site metadata (headerTitle, about, contacts, newsletter settings)
--   - Lightweight curated list of books for fast storefront rendering
--     (each entry: id/title/coverUrl/buyLink/short description/status)
-- Notes:
--   - Does not store full book content; rich content lives in `ebooks.book_json`
--   - Suitable for public pages needing quick, small payloads
CREATE TABLE IF NOT EXISTS ebooks_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_json TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'draft',
    CONSTRAINT chk_ebooks_content_status CHECK (status IN ('draft','published'))
);

-- Ebook covers stored as blobs (PostgreSQL: BYTEA)
CREATE TABLE IF NOT EXISTS ebooks_covers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(255),
    mime_type VARCHAR(100),
    data BYTEA NOT NULL,
    content_hash VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Prevent duplicate cover storage: unique by SHA-256 hash
CREATE UNIQUE INDEX IF NOT EXISTS ux_ebooks_covers_hash ON ebooks_covers(content_hash);

-- Per-ebook table: Full content per item (many rows)
-- Purpose:
--   - One row per ebook with full authoring content in `book_json`
--     (preface, disclaimer, chapters, research/ideation, questions, TOC, etc.)
--   - Fields for item-level state: title, cover_url, status, updated_at
-- Notes:
--   - Public listings should query only published rows or use `ebooks_content`
--   - Authoring flows (draft/publish) read/write here
CREATE TABLE IF NOT EXISTS ebooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    book_json TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    cover_url VARCHAR(500),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ebooks_status ON ebooks(status);
CREATE INDEX IF NOT EXISTS idx_ebooks_updated_at ON ebooks(updated_at);
ALTER TABLE ebooks ADD CONSTRAINT chk_ebooks_status CHECK (status IN ('draft','published'));

-- Newsletter subscribers (for ebooks newsletter signups)
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    unsubscribed_at TIMESTAMP
);