-- Migration: Create author_data table for Author Page info
CREATE TABLE IF NOT EXISTS author_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    bio TEXT,
    contact_email VARCHAR(255),
    social_links TEXT, -- JSON or comma-separated
    profile_image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Add more columns as needed to match Author Page fields
